# Generated by Django 5.2.10 on 2026-02-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('FARMER', 'Farmer'), ('CUSTOMER', 'Customer'), ('ADMIN', 'Admin')], max_length=20),
        ),
    ]
