import { createContext, useContext, useEffect, useMemo, useState } from "react";

const LANGUAGE_KEY = "agroconnect_language";

const translations = {
  en: {
    language: "Language",
    home: "Home",
    marketplace: "Marketplace",
    cart: "Cart",
    orders: "Orders",
    dashboard: "Dashboard",
    login: "Login",
    register: "Register",
    logout: "Logout",
    search: "Search",
    searchPlaceholder: "Search crops, regions, farms",
    connectNow: "Connect Now",
    postCrop: "Post Crop",
    browseMarketplace: "Browse Marketplace",
    filters: "Filters",
    refineResults: "Refine results",
    reset: "Reset",
    availableCrops: "Available Crops",
    resultsReady: "results ready",
    myOrders: "My Orders",
    loadingOrders: "Loading orders...",
    noOrdersYet: "No orders yet.",
    noMatchingOrders: "No matching orders",
    payment: "Payment",
    orderId: "Order ID",
    crop: "Crop",
    quantityKg: "Quantity (kg)",
    totalRs: "Total (Rs)",
    status: "Status",
    action: "Action",
    allStatuses: "All statuses",
    pending: "Pending",
    confirmed: "Confirmed",
    cancelled: "Cancelled",
    newest: "Newest",
    oldest: "Oldest",
    quantityHighToLow: "Quantity: High to Low",
    quantityLowToHigh: "Quantity: Low to High",
    priceHighToLow: "Price: High to Low",
    priceLowToHigh: "Price: Low to High",
    confirm: "Confirm",
    reject: "Reject",
    prev: "Prev",
    next: "Next",
    pageOf: "Page {page} of {totalPages}",
    cropMarketplace: "Crop Marketplace",
    browseFreshCrops: "Browse fresh crops directly from farmers.",
    totalOrders: "Total Orders",
    pendingOrders: "Pending Orders",
    confirmedOrders: "Confirmed Orders",
    totalSpent: "Total Spent",
    recentOrders7Days: "Recent Orders (7 Days)",
    cancelledOrders: "Cancelled Orders",
    farmerDashboard: "Farmer Dashboard",
    addCrop: "Add Crop",
    inventoryOverview: "Inventory Overview",
    totalCrops: "Total Crops",
    totalStockKg: "Total Stock (kg)",
    confirmedRevenue: "Confirmed Revenue",
    ordersLast7Days: "Orders (Last 7 Days)",
    farmProfile: "Farm Profile",
    saveProfile: "Save Profile",
    orderSummaryTitle: "Order Summary",
    loading: "Loading...",
    noCropsAddedYet: "No crops added yet",
    pleaseLoginCustomer: "Please log in as a customer to view your orders.",
    couldNotLoadOrders: "Could not load orders. Please try again.",
    cropNotFound: "Crop not found.",
    loadingCrop: "Loading crop...",
    loadingReviews: "Loading reviews...",
    beFirstReview: "No reviews yet. Be the first!",
    submitReview: "Submit Review",
    submitting: "Submitting...",
    addReviewVerified: "Add your review (verified buyers only)",
    rating: "Rating",
    shareExperience: "Share your experience...",
    quantity: "Quantity",
    pricePerKg: "Price per kg",
    available: "Available",
    farmer: "Farmer",
    recipientName: "Recipient name",
    mobile10Digit: "10-digit mobile",
    postalCode: "Postal code",
    houseStreetArea: "House no, Street, Area",
    landmarkApartment: "Landmark, Apartment",
    save: "Save",
    editCrop: "Edit Crop",
    addCropTitle: "Add Crop",
    cropName: "Crop Name",
    category: "Category",
    shortDescription: "Short description",
    harvestDate: "Harvest Date",
    harvestDateFuture: "Harvest date cannot be in the future.",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    deleteCropConfirm: "Delete this crop?",
    profileUpdateFailed: "Profile update failed",
    statusUpdateFailed: "Status update failed",
    completeDeliveryAddress: "Please complete the delivery address.",
    orderFailed: "Order failed",
  trustedSourcing: "Trusted sourcing for farmers, wholesalers, and households",
    homeHeroTitle:
      "Agricultural trade with a cleaner system, stronger trust, and faster action.",
    homeHeroText:
      "AgroConnect helps growers list crops professionally, helps buyers discover verified produce quickly, and keeps transactions feeling modern from first search to final order.",
    accountAccess: "Account access",
    loginTitle: "Login to AgroConnect",
    loginText: "Continue to your marketplace tools, live crop listings, and order updates.",
    username: "Username",
    password: "Password",
    enterUsername: "Enter your username",
    enterPassword: "Enter your password",
    newHere: "New here?",
    createAccount: "Create account",
    startTrading: "Start trading",
    registerTitle: "Join AgroConnect",
    registerText:
      "Create a professional buyer or farmer account and move from discovery to transaction in one connected platform.",
    email: "Email",
    confirmPassword: "Confirm Password",
    registerAs: "Register as",
    customerRole: "Customer (Buy Crops)",
    farmerRole: "Farmer (Sell Crops)",
    farmName: "Farm Name",
    location: "Location",
    address: "Address",
    alreadyHaveAccount: "Already have an account?",
    yourCart: "Your Cart",
    cartText: "Review selected crops and continue to delivery.",
    clearCart: "Clear Cart",
    emptyCart: "Your cart is empty.",
    browseCrops: "Browse Crops",
    orderSummary: "Order Summary",
    subtotal: "Subtotal",
    delivery: "Delivery",
    free: "Free",
    total: "Total",
    proceedToCheckout: "Proceed to Checkout",
    checkout: "Checkout",
    checkoutText: "Confirm delivery details and place the order.",
    backToCart: "Back to cart",
    deliveryAddress: "Delivery Address",
    fullName: "Full Name",
    phone: "Phone",
    pincode: "Pincode",
    addressLine1: "Address Line 1",
    addressLine2: "Address Line 2",
    city: "City",
    state: "State",
    paymentMethod: "Payment Method",
    placeOrder: "Place Order",
    backToMarketplace: "Back to marketplace",
    customerReviews: "Customer reviews",
    noReviewsYet: "No reviews yet.",
    availableStock: "Available stock",
    buyNow: "Buy Now",
    addToCart: "Add to Cart",
    deliveryQuality: "Delivery & quality",
    directFromFarmers: "Direct from verified farmers",
    qualityChecked: "Quality-checked before dispatch",
    securePackaging: "Secure packaging & cold chain",
    farmersOnly: "Farm Commerce Platform",
  },
  hi: {
    language: "भाषा",
    home: "होम",
    marketplace: "मार्केटप्लेस",
    cart: "कार्ट",
    orders: "ऑर्डर",
    dashboard: "डैशबोर्ड",
    login: "लॉग इन",
    register: "रजिस्टर",
    logout: "लॉग आउट",
    search: "खोजें",
    searchPlaceholder: "फसल, क्षेत्र, फार्म खोजें",
    connectNow: "अभी जुड़ें",
    postCrop: "फसल पोस्ट करें",
    browseMarketplace: "मार्केटप्लेस देखें",
    filters: "फ़िल्टर",
    refineResults: "परिणाम छाँटें",
    reset: "रीसेट",
    availableCrops: "उपलब्ध फसलें",
    resultsReady: "परिणाम तैयार",
    myOrders: "मेरे ऑर्डर",
    loadingOrders: "ऑर्डर लोड हो रहे हैं...",
    noOrdersYet: "अभी तक कोई ऑर्डर नहीं।",
    noMatchingOrders: "कोई मिलते-जुलते ऑर्डर नहीं",
    payment: "भुगतान",
    orderId: "ऑर्डर आईडी",
    crop: "फसल",
    quantityKg: "मात्रा (किलो)",
    totalRs: "कुल (रु)",
    status: "स्थिति",
    action: "कार्रवाई",
    allStatuses: "सभी स्थितियां",
    pending: "लंबित",
    confirmed: "पुष्ट",
    cancelled: "रद्द",
    newest: "नवीनतम",
    oldest: "पुराना",
    quantityHighToLow: "मात्रा: अधिक से कम",
    quantityLowToHigh: "मात्रा: कम से अधिक",
    priceHighToLow: "कीमत: अधिक से कम",
    priceLowToHigh: "कीमत: कम से अधिक",
    confirm: "पुष्टि करें",
    reject: "अस्वीकार करें",
    prev: "पिछला",
    next: "अगला",
    pageOf: "पेज {page} / {totalPages}",
    cropMarketplace: "फसल मार्केटप्लेस",
    browseFreshCrops: "ताज़ी फसलें सीधे किसानों से देखें।",
    totalOrders: "कुल ऑर्डर",
    pendingOrders: "लंबित ऑर्डर",
    confirmedOrders: "पुष्ट ऑर्डर",
    totalSpent: "कुल खर्च",
    recentOrders7Days: "हाल के ऑर्डर (7 दिन)",
    cancelledOrders: "रद्द ऑर्डर",
    farmerDashboard: "किसान डैशबोर्ड",
    addCrop: "फसल जोड़ें",
    inventoryOverview: "इन्वेंट्री अवलोकन",
    totalCrops: "कुल फसलें",
    totalStockKg: "कुल स्टॉक (किलो)",
    confirmedRevenue: "पुष्ट राजस्व",
    ordersLast7Days: "ऑर्डर (पिछले 7 दिन)",
    farmProfile: "फार्म प्रोफ़ाइल",
    saveProfile: "प्रोफ़ाइल सहेजें",
    orderSummaryTitle: "ऑर्डर सारांश",
    loading: "लोड हो रहा है...",
    noCropsAddedYet: "अभी तक कोई फसल नहीं जोड़ी गई",
    pleaseLoginCustomer: "अपने ऑर्डर देखने के लिए ग्राहक के रूप में लॉग इन करें।",
    couldNotLoadOrders: "ऑर्डर लोड नहीं हो सके। कृपया फिर से प्रयास करें।",
    cropNotFound: "फसल नहीं मिली।",
    loadingCrop: "फसल लोड हो रही है...",
    loadingReviews: "समीक्षाएं लोड हो रही हैं...",
    beFirstReview: "अभी तक कोई समीक्षा नहीं। पहली समीक्षा करें!",
    submitReview: "समीक्षा भेजें",
    submitting: "भेजा जा रहा है...",
    addReviewVerified: "अपनी समीक्षा जोड़ें (केवल सत्यापित खरीदार)",
    rating: "रेटिंग",
    shareExperience: "अपना अनुभव साझा करें...",
    quantity: "मात्रा",
    pricePerKg: "प्रति किलो कीमत",
    available: "उपलब्ध",
    farmer: "किसान",
    recipientName: "प्राप्तकर्ता का नाम",
    mobile10Digit: "10 अंकों का मोबाइल",
    postalCode: "पोस्टल कोड",
    houseStreetArea: "मकान नं., गली, क्षेत्र",
    landmarkApartment: "लैंडमार्क, अपार्टमेंट",
    save: "सहेजें",
    editCrop: "फसल संपादित करें",
    addCropTitle: "फसल जोड़ें",
    cropName: "फसल का नाम",
    category: "श्रेणी",
    shortDescription: "संक्षिप्त विवरण",
    harvestDate: "कटाई की तारीख",
    harvestDateFuture: "कटाई की तारीख भविष्य की नहीं हो सकती।",
    cancel: "रद्द करें",
    edit: "संपादित करें",
    delete: "हटाएं",
    deleteCropConfirm: "क्या इस फसल को हटाना है?",
    profileUpdateFailed: "प्रोफ़ाइल अपडेट विफल रहा",
    statusUpdateFailed: "स्थिति अपडेट विफल रहा",
    completeDeliveryAddress: "कृपया डिलीवरी पता पूरा करें।",
    orderFailed: "ऑर्डर विफल रहा",
    trustedSourcing: "किसानों, थोक खरीदारों और परिवारों के लिए भरोसेमंद सोर्सिंग",
    homeHeroTitle:
      "कृषि व्यापार के लिए अधिक साफ, भरोसेमंद और तेज़ डिजिटल अनुभव।",
    homeHeroText:
      "AgroConnect किसानों को पेशेवर ढंग से फसल सूचीबद्ध करने, खरीदारों को सत्यापित उत्पाद जल्दी खोजने और पूरे लेनदेन को आधुनिक बनाने में मदद करता है।",
    accountAccess: "खाता प्रवेश",
    loginTitle: "AgroConnect में लॉग इन करें",
    loginText: "अपने मार्केटप्लेस टूल्स, लाइव फसल लिस्टिंग और ऑर्डर अपडेट देखें।",
    username: "यूज़रनेम",
    password: "पासवर्ड",
    enterUsername: "अपना यूज़रनेम दर्ज करें",
    enterPassword: "अपना पासवर्ड दर्ज करें",
    newHere: "नए हैं?",
    createAccount: "खाता बनाएं",
    startTrading: "व्यापार शुरू करें",
    registerTitle: "AgroConnect से जुड़ें",
    registerText:
      "खरीदार या किसान के रूप में पेशेवर खाता बनाएं और खोज से लेनदेन तक एक ही प्लेटफॉर्म पर जाएं।",
    email: "ईमेल",
    confirmPassword: "पासवर्ड की पुष्टि करें",
    registerAs: "रजिस्टर करें",
    customerRole: "ग्राहक (फसल खरीदें)",
    farmerRole: "किसान (फसल बेचें)",
    farmName: "फार्म का नाम",
    location: "स्थान",
    address: "पता",
    alreadyHaveAccount: "पहले से खाता है?",
    yourCart: "आपका कार्ट",
    cartText: "चुनी गई फसलों की समीक्षा करें और डिलीवरी जारी रखें।",
    clearCart: "कार्ट खाली करें",
    emptyCart: "आपका कार्ट खाली है।",
    browseCrops: "फसलें देखें",
    orderSummary: "ऑर्डर सारांश",
    subtotal: "उप-योग",
    delivery: "डिलीवरी",
    free: "मुफ़्त",
    total: "कुल",
    proceedToCheckout: "चेकआउट पर जाएं",
    checkout: "चेकआउट",
    checkoutText: "डिलीवरी विवरण की पुष्टि करें और ऑर्डर करें।",
    backToCart: "कार्ट पर वापस जाएं",
    deliveryAddress: "डिलीवरी पता",
    fullName: "पूरा नाम",
    phone: "फ़ोन",
    pincode: "पिनकोड",
    addressLine1: "पता पंक्ति 1",
    addressLine2: "पता पंक्ति 2",
    city: "शहर",
    state: "राज्य",
    paymentMethod: "भुगतान विधि",
    placeOrder: "ऑर्डर करें",
    backToMarketplace: "मार्केटप्लेस पर वापस",
    customerReviews: "ग्राहक समीक्षाएं",
    noReviewsYet: "अभी तक कोई समीक्षा नहीं।",
    availableStock: "उपलब्ध स्टॉक",
    buyNow: "अभी खरीदें",
    addToCart: "कार्ट में जोड़ें",
    deliveryQuality: "डिलीवरी और गुणवत्ता",
    directFromFarmers: "सत्यापित किसानों से सीधे",
    qualityChecked: "भेजने से पहले गुणवत्ता जांच",
    securePackaging: "सुरक्षित पैकेजिंग और कोल्ड चेन",
    farmersOnly: "फार्म कॉमर्स प्लेटफॉर्म",
  },
  te: {
    language: "భాష",
    home: "హోమ్",
    marketplace: "మార్కెట్‌ప్లేస్",
    cart: "కార్ట్",
    orders: "ఆర్డర్లు",
    dashboard: "డ్యాష్‌బోర్డ్",
    login: "లాగిన్",
    register: "రిజిస్టర్",
    logout: "లాగ్ఔట్",
    search: "వెతకండి",
    searchPlaceholder: "పంటలు, ప్రాంతాలు, ఫార్ములు వెతకండి",
    connectNow: "ఇప్పుడే కలవండి",
    postCrop: "పంట పోస్ట్ చేయండి",
    browseMarketplace: "మార్కెట్‌ప్లేస్ చూడండి",
    filters: "ఫిల్టర్లు",
    refineResults: "ఫలితాలను మెరుగుపరచండి",
    reset: "రీసెట్",
    availableCrops: "అందుబాటులో ఉన్న పంటలు",
    resultsReady: "ఫలితాలు సిద్ధం",
    myOrders: "నా ఆర్డర్లు",
    loadingOrders: "ఆర్డర్లు లోడ్ అవుతున్నాయి...",
    noOrdersYet: "ఇంకా ఆర్డర్లు లేవు.",
    noMatchingOrders: "సరిపోలే ఆర్డర్లు లేవు",
    payment: "చెల్లింపు",
    orderId: "ఆర్డర్ ఐడి",
    crop: "పంట",
    quantityKg: "పరిమాణం (కిలో)",
    totalRs: "మొత్తం (రూ)",
    status: "స్థితి",
    action: "చర్య",
    allStatuses: "అన్ని స్థితులు",
    pending: "పెండింగ్",
    confirmed: "నిర్ధారితం",
    cancelled: "రద్దు",
    newest: "కొత్తవి",
    oldest: "పాతవి",
    quantityHighToLow: "పరిమాణం: ఎక్కువ నుండి తక్కువ",
    quantityLowToHigh: "పరిమాణం: తక్కువ నుండి ఎక్కువ",
    priceHighToLow: "ధర: ఎక్కువ నుండి తక్కువ",
    priceLowToHigh: "ధర: తక్కువ నుండి ఎక్కువ",
    confirm: "నిర్ధారించండి",
    reject: "తిరస్కరించండి",
    prev: "మునుపటి",
    next: "తదుపరి",
    pageOf: "పేజీ {page} / {totalPages}",
    cropMarketplace: "పంట మార్కెట్‌ప్లేస్",
    browseFreshCrops: "తాజా పంటలను నేరుగా రైతుల నుండి చూడండి.",
    totalOrders: "మొత్తం ఆర్డర్లు",
    pendingOrders: "పెండింగ్ ఆర్డర్లు",
    confirmedOrders: "నిర్ధారిత ఆర్డర్లు",
    totalSpent: "మొత్తం ఖర్చు",
    recentOrders7Days: "ఇటీవలి ఆర్డర్లు (7 రోజులు)",
    cancelledOrders: "రద్దైన ఆర్డర్లు",
    farmerDashboard: "రైతు డ్యాష్‌బోర్డ్",
    addCrop: "పంట జోడించండి",
    inventoryOverview: "ఇన్వెంటరీ అవలోకనం",
    totalCrops: "మొత్తం పంటలు",
    totalStockKg: "మొత్తం స్టాక్ (కిలో)",
    confirmedRevenue: "నిర్ధారిత ఆదాయం",
    ordersLast7Days: "ఆర్డర్లు (గత 7 రోజులు)",
    farmProfile: "ఫారం ప్రొఫైల్",
    saveProfile: "ప్రొఫైల్ సేవ్ చేయండి",
    orderSummaryTitle: "ఆర్డర్ సారాంశం",
    loading: "లోడ్ అవుతోంది...",
    noCropsAddedYet: "ఇంకా పంటలు జోడించలేదు",
    pleaseLoginCustomer: "మీ ఆర్డర్లు చూడటానికి కస్టమర్‌గా లాగిన్ అవ్వండి.",
    couldNotLoadOrders: "ఆర్డర్లు లోడ్ కాలేదు. మళ్లీ ప్రయత్నించండి.",
    cropNotFound: "పంట కనబడలేదు.",
    loadingCrop: "పంట లోడ్ అవుతోంది...",
    loadingReviews: "సమీక్షలు లోడ్ అవుతున్నాయి...",
    beFirstReview: "ఇంకా సమీక్షలు లేవు. మొదటిది మీరు ఇవ్వండి!",
    submitReview: "సమీక్ష సమర్పించండి",
    submitting: "సమర్పిస్తోంది...",
    addReviewVerified: "మీ సమీక్షను జోడించండి (ధృవీకరించిన కొనుగోలుదారులు మాత్రమే)",
    rating: "రేటింగ్",
    shareExperience: "మీ అనుభవాన్ని పంచుకోండి...",
    quantity: "పరిమాణం",
    pricePerKg: "కిలోకు ధర",
    available: "అందుబాటులో",
    farmer: "రైతు",
    recipientName: "గ్రహీత పేరు",
    mobile10Digit: "10 అంకెల మొబైల్",
    postalCode: "పోస్టల్ కోడ్",
    houseStreetArea: "ఇంటి నం., వీధి, ప్రాంతం",
    landmarkApartment: "ల్యాండ్‌మార్క్, అపార్ట్‌మెంట్",
    save: "సేవ్ చేయండి",
    editCrop: "పంట సవరించండి",
    addCropTitle: "పంట జోడించండి",
    cropName: "పంట పేరు",
    category: "వర్గం",
    shortDescription: "చిన్న వివరణ",
    harvestDate: "పంట కోత తేదీ",
    harvestDateFuture: "పంట కోత తేదీ భవిష్యత్తులో ఉండకూడదు.",
    cancel: "రద్దు చేయండి",
    edit: "సవరించండి",
    delete: "తొలగించండి",
    deleteCropConfirm: "ఈ పంటను తొలగించాలా?",
    profileUpdateFailed: "ప్రొఫైల్ అప్డేట్ విఫలమైంది",
    statusUpdateFailed: "స్థితి అప్డేట్ విఫలమైంది",
    completeDeliveryAddress: "దయచేసి డెలివరీ చిరునామాను పూర్తి చేయండి.",
    orderFailed: "ఆర్డర్ విఫలమైంది",
    trustedSourcing: "రైతులు, హోల్‌సేలర్లు, కుటుంబాల కోసం నమ్మదగిన సోర్సింగ్",
    homeHeroTitle:
      "వ్యవసాయ వాణిజ్యానికి మరింత స్పష్టమైన, నమ్మదగిన, వేగమైన డిజిటల్ అనుభవం.",
    homeHeroText:
      "AgroConnect రైతులు పంటలను ప్రొఫెషనల్‌గా లిస్ట్ చేయడానికి, కొనుగోలుదారులు ధృవీకరించిన ఉత్పత్తులను త్వరగా కనుగొనడానికి, మొత్తం లావాదేవీని ఆధునికంగా అనిపించేలా చేస్తుంది.",
    accountAccess: "ఖాతా ప్రవేశం",
    loginTitle: "AgroConnect లో లాగిన్ అవ్వండి",
    loginText: "మీ మార్కెట్ టూల్స్, ప్రత్యక్ష పంట జాబితాలు, ఆర్డర్ అప్డేట్లను కొనసాగించండి.",
    username: "యూజర్‌నేమ్",
    password: "పాస్‌వర్డ్",
    enterUsername: "మీ యూజర్‌నేమ్ నమోదు చేయండి",
    enterPassword: "మీ పాస్‌వర్డ్ నమోదు చేయండి",
    newHere: "కొత్తవారా?",
    createAccount: "ఖాతా సృష్టించండి",
    startTrading: "వ్యాపారం ప్రారంభించండి",
    registerTitle: "AgroConnect లో చేరండి",
    registerText:
      "కొనుగోలుదారు లేదా రైతుగా ప్రొఫెషనల్ ఖాతా సృష్టించి, కనుగొనడం నుంచి లావాదేవీ వరకు ఒకే ప్లాట్‌ఫామ్‌లో కొనసాగండి.",
    email: "ఈమెయిల్",
    confirmPassword: "పాస్‌వర్డ్ నిర్ధారించండి",
    registerAs: "రిజిస్టర్ అవ్వండి",
    customerRole: "కస్టమర్ (పంటలు కొనండి)",
    farmerRole: "రైతు (పంటలు అమ్మండి)",
    farmName: "ఫారం పేరు",
    location: "ప్రాంతం",
    address: "చిరునామా",
    alreadyHaveAccount: "ఇప్పటికే ఖాతా ఉందా?",
    yourCart: "మీ కార్ట్",
    cartText: "ఎంచుకున్న పంటలను సమీక్షించి డెలివరీకి కొనసాగండి.",
    clearCart: "కార్ట్ ఖాళీ చేయండి",
    emptyCart: "మీ కార్ట్ ఖాళీగా ఉంది.",
    browseCrops: "పంటలు చూడండి",
    orderSummary: "ఆర్డర్ సారాంశం",
    subtotal: "ఉప మొత్తం",
    delivery: "డెలివరీ",
    free: "ఉచితం",
    total: "మొత్తం",
    proceedToCheckout: "చెకౌట్‌కు వెళ్లండి",
    checkout: "చెకౌట్",
    checkoutText: "డెలివరీ వివరాలు ధృవీకరించి ఆర్డర్ ఇవ్వండి.",
    backToCart: "కార్ట్‌కు తిరిగి",
    deliveryAddress: "డెలివరీ చిరునామా",
    fullName: "పూర్తి పేరు",
    phone: "ఫోన్",
    pincode: "పిన్‌కోడ్",
    addressLine1: "చిరునామా లైన్ 1",
    addressLine2: "చిరునామా లైన్ 2",
    city: "నగరం",
    state: "రాష్ట్రం",
    paymentMethod: "చెల్లింపు విధానం",
    placeOrder: "ఆర్డర్ ఇవ్వండి",
    backToMarketplace: "మార్కెట్‌ప్లేస్‌కు తిరిగి",
    customerReviews: "కస్టమర్ సమీక్షలు",
    noReviewsYet: "ఇంకా సమీక్షలు లేవు.",
    availableStock: "అందుబాటులో స్టాక్",
    buyNow: "ఇప్పుడే కొనండి",
    addToCart: "కార్ట్‌లో చేర్చండి",
    deliveryQuality: "డెలివరీ మరియు నాణ్యత",
    directFromFarmers: "ధృవీకరించిన రైతుల నుంచి నేరుగా",
    qualityChecked: "డిస్పాచ్ ముందు నాణ్యత తనిఖీ",
    securePackaging: "సురక్షిత ప్యాకేజింగ్ మరియు కోల్డ్ చైన్",
    farmersOnly: "ఫార్మ్ కామర్స్ ప్లాట్‌ఫారం",
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(
    () => localStorage.getItem(LANGUAGE_KEY) || "en"
  );

  useEffect(() => {
    localStorage.setItem(LANGUAGE_KEY, language);
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: (key, fallback = key) =>
        translations[language]?.[key] ?? translations.en[key] ?? fallback,
    }),
    [language]
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used inside LanguageProvider");
  }
  return context;
}
